apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: "https://103.185.52.45:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpFek9UQTRNRFF3SGhjTk1qWXdNakU0TURVd01EQTBXaGNOTXpZd01qRTJNRFV3TURBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpFek9UQTRNRFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTckpZTUNCdG9kU2lGZ2k1bkJ0YnNRaE4wcTRnSmRJQ2lzeGRwN2FGR00KcTVaWk5iQXpLbjNrd05hU2JmZ2sxL2xUQWFIWnFSUlI0czdqaEFIclhUMjZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXdHdVk4YVZ2QzVURDZnaUdFQlNTCmRrK2loU2t3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnYld1Y1NkQUVsZ3orcmp2Z1hrU0hXTTRSQnlrQVo4VjQKWDBlTjhYZzdJMmNDSVFDZWRtR2pVMzVQaUtheVFnQS9NWHJMd2ZyL1pBeUU3eUJzWHo2bGN5VFZKZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
contexts:
- name: kanarazu-katsu
  context:
    cluster: local
    namespace: kanarazu-katsu
    user: kanarazu-katsu-sa
current-context: kanarazu-katsu
users:
- name: kanarazu-katsu-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlFteFl2cGk1RkF5TEFkdDJYSC05UnVmUGJhYXJCU0pBNjNEcUZxcEtsdFUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrYW5hcmF6dS1rYXRzdSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrYW5hcmF6dS1rYXRzdS1zYS10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrYW5hcmF6dS1rYXRzdS1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImI3MWFkYzM4LTQ5ZGItNDhhMy04YmNiLTcwOGIzNzY1NGYwNSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprYW5hcmF6dS1rYXRzdTprYW5hcmF6dS1rYXRzdS1zYSJ9.TpPeRMcUVR_hBNUJG-XOzRe8j-nTqe8mclRoH9kUK0RBXGkZNmOC2kwTWvIettQTGzPQYjAkliVdwXovd8yF0JxlaDhLYUt7vD11QlbhSrbJx4Ah78tziu35-MJF7VCGnIq7ePjpFIwyyjPmlVayH3BI1CPmqixMMKGSXHVT_xXphDjBYcf6H6qJuBkcoJNuo8CEP2qybh_2Vc9Jpxf30iH5XtoXobawsM-Cha-dk-80Wm5jF20xZIxAic4jrC9zmRwcei-65af4p8dUT2MoKaOlvMeng-2jrBfkI2iX8dRSQwp5ABQJez8Z-Mqjcnan7B4brDU5yWTAa-DYxCaCDg
