<?php

namespace Database\Seeders;

use App\Models\Guide;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class GuideSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $guides = [
            [
                'title' => 'Tata Cara Evakuasi Saat Gempa Bumi',
                'slug' => 'tata-cara-evakuasi-saat-gempa-bumi',
                'category' => 'earthquake',
                'content' => '<p>Panduan lengkap evakuasi saat terjadi gempa bumi untuk menjaga keselamatan diri dan keluarga.</p>',
                'steps' => [
                    ['title' => 'Saat Gempa Terjadi', 'description' => 'Drop, Cover, and Hold On. Jatuhkan diri ke lantai, berlindung di bawah meja/kekuat, dan tunggu hingga gempa berhenti.'],
                    ['title' => 'Evaluasi Kerusakan', 'description' => 'Setelah gempa, periksa diri sendiri dan orang lain untuk cedera. Jangan masuk ke dalam bangunan yang rusak.'],
                    ['title' => 'Siapkan Aftershock', 'description' => 'Bersiap untuk gempa susulan. Simpan persediaan darurat dan tetap waspada.'],
                    ['title' => 'Ikuti Instruksi Evakuasi', 'description' => 'Ikuti petunjuk petugas SAR dan evakuasi ke tempat aman yang ditentukan.'],
                ],
                'image' => 'images/guides/gempa-bumi-evakuasi.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=HLJdK5E1I2I',
                'status' => 'published',
            ],
            [
                'title' => 'Panduan Menghadapi Banjir',
                'slug' => 'panduan-menghadapi-banjir',
                'category' => 'flood',
                'content' => '<p>Banjir adalah bencana yang sering terjadi di Indonesia. Ketahui cara menghadapinya.</p>',
                'steps' => [
                    ['title' => 'Pantau Peringatan Dini', 'description' => 'Ikuti informasi dari BMKG dan BPBD. Siapkan tas darurat jika diperlukan evakuasi.'],
                    ['title' => 'Pindahkan Barang Berharga', 'description' => 'Angkat perabot dan barang elektronik ke tempat tinggi. Matikan listrik dan gas.'],
                    ['title' => 'Evakuasi ke Tempat Tinggi', 'description' => 'Jika air naik cepat, segera ke lantai atas atau titik evakuasi. Jangan berjalan melalui air yang mengalir.'],
                    ['title' => 'Hindari Air Banjir', 'description' => 'Air banjir bisa terkontaminasi dan berbahaya. Jangan minum atau bermain di air banjir.'],
                ],
                'image' => 'images/guides/banjir-evakuasi.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=8bWu3H9_5fE',
                'status' => 'published',
            ],
            [
                'title' => 'Protokol Erupsi Gunung Berapi',
                'slug' => 'protokol-erupsi-gunung-berapi',
                'category' => 'volcano',
                'content' => '<p>Ketahui apa yang harus dilakukan saat gunung berapi erupsi.</p>',
                'steps' => [
                    ['title' => 'Kenali Radius Bahaya', 'description' => 'Perhatikan status gunung api dan radius bahaya yang ditetapkan oleh PVMBG.'],
                    ['title' => 'Siapkan Masker', 'description' => 'Gunakan masker N95 atau kain basah saat ada abu vulkanik. Hindari area dengan konsentrasi abu tinggi.'],
                    ['title' => 'Lindungi Mata dan Kulit', 'description' => 'Gunakan kacamata pelindung dan tutupi kulit. Abu vulkanik bisa mengiritasi.'],
                    ['title' => 'Bersihkan Atap', 'description' => 'Keluarkan abu dari atap untuk mencegah keruntuhan. Hati-hati saat membersihkan.'],
                ],
                'image' => 'images/guides/erupsi-gunung.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0P2Mwp4_m8E',
                'status' => 'published',
            ],
            [
                'title' => 'Pertolongan Pertama Dasar',
                'slug' => 'pertolongan-pertama-dasar',
                'category' => 'general',
                'content' => '<p>Keterampilan pertolongan pertama bisa menyelamatkan nyawa saat bencana.</p>',
                'steps' => [
                    ['title' => 'Pemeriksaan ABC', 'description' => 'Airway (jalan napas), Breathing (pernapasan), Circulation (sirkulasi darah). Pastikan ketiganya lancar.'],
                    ['title' => 'Kontrol Pendarahan', 'description' => 'Tekan luka yang berdarah dengan kain bersih. Angkat bagian tubuh yang terluka di atas jantung jika memungkinkan.'],
                    ['title' => 'Patah Tulang', 'description' => 'Imobilisasi bagian yang patah dengan splint. Jangan mencoba membetulkan sendiri.'],
                    ['title' => 'Shock', 'description' => 'Tanda shock: kulit pucat, dingin, dan berkeringat. Berikan kenyamanan dan hangat. Cari bantuan medis segera.'],
                ],
                'image' => 'images/guides/pertolongan-pertama.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=Gw5Gjpw80aQ',
                'status' => 'published',
            ],
            [
                'title' => 'Persiapan Tas Darurat (Emergency Kit)',
                'slug' => 'persiapan-tas-darurat-emergency-kit',
                'category' => 'general',
                'content' => '<p>Tas darurat yang lengkap bisa menyelamatkan hidup Anda saat bencana.</p>',
                'steps' => [
                    ['title' => 'Air dan Makanan', 'description' => 'Minimal 3 liter air per orang per hari dan makanan tahan lama untuk 3 hari (kaleng, kering, energi bar).'],
                    ['title' => 'Obat-obatan', 'description' => 'Kotak P3K pribadi, obat rutin, dan resep dokter. Termasuk masker dan hand sanitizer.'],
                    ['title' => 'Dokumen Penting', 'description' => 'KTP, KK, SIM, sertifikat tanah, polis asuransi, dan uang tunai dalam jumlah kecil dalam wadah kedap air.'],
                    ['title' => 'Peralatan', 'description' => 'Senter, radio portabel, baterai cadangan, power bank, pisau multi-fungsi, dan selimut darurat.'],
                ],
                'image' => 'images/guides/tas-darurat.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=3ICV9xO2RjQ',
                'status' => 'published',
            ],
            [
                'title' => 'Evakuasi Saat Tsunami',
                'slug' => 'evakuasi-saat-tsunami',
                'category' => 'tsunami',
                'content' => '<p>Tsunami datang tanpa peringatan. Ketahui cara evakuasi yang benar untuk menyelamatkan diri.</p>',
                'steps' => [
                    ['title' => 'Kenali Tanda Alam', 'description' => 'Gempa bumi yang kuat, air laut yang tiba-tiba surut, atau suara gemuruh dari laut adalah tanda tsunami.'],
                    ['title' => 'Segera ke Tempat Tinggi', 'description' => 'Jika merasakan gempa kuat di dekat pantai, segera lari ke tempat tinggi minimal 30 meter dari permukaan laut.'],
                    ['title' => 'Jangan Tunggu Peringatan', 'description' => 'Jangan menunggu peringatan resmi. Segera evakuasi begitu merasakan gempa kuat.'],
                    ['title' => 'Hindari Daerah Pesisir', 'description' => 'Tetap di tempat tinggi sampai ada konfirmasi resmi bahwa tsunami tidak akan datang atau sudah lewat.'],
                ],
                'image' => 'images/guides/tsunami-evakuasi.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=7CqJ5xWqZfE',
                'status' => 'published',
            ],
            [
                'title' => 'Protokol Kebakaran Rumah',
                'slug' => 'protokol-kebakaran-rumah',
                'category' => 'fire',
                'content' => '<p>Kebakaran rumah dapat menyebar dengan cepat. Ketahui cara menghadapinya dengan benar.</p>',
                'steps' => [
                    ['title' => 'Hubungi Pemadam Kebakaran', 'description' => 'Segera hubungi 113 atau nomor pemadam kebakaran setempat. Berikan alamat yang jelas.'],
                    ['title' => 'Evakuasi Segera', 'description' => 'Keluar dari rumah secepat mungkin. Jangan kembali mengambil barang berharga.'],
                    ['title' => 'Merangkak di Bawah Asap', 'description' => 'Asap naik ke atas. Merangkaklah di lantai untuk mendapatkan udara bersih saat evakuasi.'],
                    ['title' => 'Periksa Pintu Sebelum Buka', 'description' => 'Raba punggung pintu sebelum membuka. Jika panas, cari jalalternatif lain.'],
                ],
                'image' => 'images/guides/kebakaran-rumah.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=PVynrzQ5lQk',
                'status' => 'published',
            ],
            [
                'title' => 'Menghadapi Tanah Longsor',
                'slug' => 'menghadapi-tanah-longsor',
                'category' => 'landslide',
                'content' => '<p>Tanah longsor sering terjadi saat hujan deras. Ketahui tanda-tanda dan cara evakuasinya.</p>',
                'steps' => [
                    ['title' => 'Kenali Tanda Longsor', 'description' => 'Air sumur berubah warna, tanah retak, pohon miring, atau suara gemuruh dari bukit.'],
                    ['title' => 'Evakuasi Segera', 'description' => 'Jika melihat tanda-tanda, segera tinggalkan rumah dan ke tempat tinggi yang aman.'],
                    ['title' => 'Jangan Melintas Sungai', 'description' => 'Hindari lewati sungai atau lembah saat hujan deras. Longsor bisa terjadi kapan saja.'],
                    ['title' => 'Hubungi Pihak Berwenang', 'description' => 'Laporkan ke BPBD atau desa setempat jika ada tanda bahaya longsor.'],
                ],
                'image' => 'images/guides/tanah-longsor.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=3kYkEVUQqXw',
                'status' => 'published',
            ],
            [
                'title' => 'Menghadapi Badai Tropis',
                'slug' => 'menghadapi-badai-tropis',
                'category' => 'storm',
                'content' => '<p>Panduan keselamatan menghadapi angin kencang dan hujan lebat akibat badai tropis.</p>',
                'steps' => [
                    ['title' => 'Amankan Jendela', 'description' => 'Tutup jendela dan pasang papan pelindung jika perlu. Jauhi jendela kaca selama badai.'],
                    ['title' => 'Bawa Masuk Barang Luar', 'description' => 'Amankan jemuran, pot bunga, dan barang yang bisa terbang tertiup angin.'],
                    ['title' => 'Siapkan Pencahayaan Cadangan', 'description' => 'Siapkan senter dan baterai cadangan. Hindari penggunaan lilin untuk mencegah kebakaran.'],
                    ['title' => 'Tetap di Dalam Ruangan', 'description' => 'Jangan keluar rumah sampai ada pengumuman resmi bahwa badai telah mereda.'],
                ],
                'image' => 'images/guides/storm-safety.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=S5XbS_cI75M',
                'status' => 'published',
            ],
            [
                'title' => 'Keselamatan Saat Angin Puting Beliung',
                'slug' => 'keselamatan-saat-angin-puting-beliung',
                'category' => 'storm',
                'content' => '<p>Tindakan cepat saat melihat atau mendengar peringatan puting beliung.</p>',
                'steps' => [
                    ['title' => 'Cari Tempat Berlindung', 'description' => 'Segera ke ruang bawah tanah atau ruangan paling tengah di lantai dasar yang tidak berjendela.'],
                    ['title' => 'Lindungi Kepala', 'description' => 'Gunakan tangan, bantal, atau helm untuk melindungi kepala dari serpihan yang terbang.'],
                    ['title' => 'Hindari Kendaraan', 'description' => 'Jangan berlindung di dalam mobil atau di bawah jembatan layang.'],
                    ['title' => 'Tiarap di Area Rendah', 'description' => 'Jika terjebak di luar, tiaraplah di parit atau area rendah dan lindungi kepala Anda.'],
                ],
                'image' => 'images/guides/tornado-safety.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=5OhXpW8Z9_c',
                'status' => 'published',
            ],
            [
                'title' => 'Mencegah Dehidrasi Saat Gelombang Panas',
                'slug' => 'mencegah-dehidrasi-saat-gelombang-panas',
                'category' => 'heatwave',
                'content' => '<p>Tips menjaga hidrasi tubuh agar tetap bugar saat suhu udara ekstrem meningkat.</p>',
                'steps' => [
                    ['title' => 'Minum Air Teratur', 'description' => 'Minum air putih setiap 15-20 menit meskipun tidak merasa haus.'],
                    ['title' => 'Hindari Kafein dan Alkohol', 'description' => 'Minuman ini dapat mempercepat hilangnya cairan tubuh.'],
                    ['title' => 'Gunakan Pakaian Ringan', 'description' => 'Pakai baju berbahan katun, berwarna cerah, dan longgar untuk sirkulasi udara.'],
                    ['title' => 'Batasi Aktivitas Luar', 'description' => 'Hindari berolahraga atau bekerja berat di bawah terik matahari antara jam 10 pagi - 4 sore.'],
                ],
                'image' => 'images/guides/heatwave-safety.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=XvK_E_5G8i0',
                'status' => 'published',
            ],
            [
                'title' => 'Penanganan Heat Stroke (Sengatan Panas)',
                'slug' => 'penanganan-heat-stroke',
                'category' => 'heatwave',
                'content' => '<p>Heat stroke adalah kondisi medis darurat yang membutuhkan penanganan segera.</p>',
                'steps' => [
                    ['title' => 'Kenali Gejala', 'description' => 'Suhu tubuh tinggi (>40C), kulit merah/kering, pusing, hingga pingsan.'],
                    ['title' => 'Pindahkan ke Tempat Teduh', 'description' => 'Segera bawa penderita ke area yang lebih dingin atau ber-AC.'],
                    ['title' => 'Dinginkan Tubuh', 'description' => 'Gunakan kain basah atau kompres es di leher, ketiak, dan selangkangan.'],
                    ['title' => 'Hubungi Medis Segera', 'description' => 'Heat stroke bisa menyebabkan kerusakan otak atau kematian jika tidak segera ditolong.'],
                ],
                'image' => 'images/guides/heat-stroke.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=3R-zVqY1XvI',
                'status' => 'published',
            ],
            [
                'title' => 'Teknik Membuat Api Tanpa Korek',
                'slug' => 'membuat-api-tanpa-korek',
                'category' => 'wilderness',
                'content' => '<p>Keterampilan dasar bertahan hidup di alam liar untuk kebutuhan hangat dan memasak.</p>',
                'steps' => [
                    ['title' => 'Siapkan Umpan Api (Tinder)', 'description' => 'Cari bahan kering seperti rumput, kulit pohon, atau serpihan kayu halus.'],
                    ['title' => 'Metode Gesekan Kayu', 'description' => 'Gunakan teknik Bow Drill atau Hand Drill untuk menciptakan bara panas.'],
                    ['title' => 'Gunakan Lensa', 'description' => 'Fokuskan cahaya matahari menggunakan lensa kacamata atau kaca pembesar ke tinder.'],
                    ['title' => 'Jaga Api Tetap Menyala', 'description' => 'Tambahkan kayu ranting secara bertahap hingga api stabil.'],
                ],
                'image' => 'guides/fire-making.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0kM1xM_R0-c',
                'status' => 'published',
            ],
            [
                'title' => 'Menemukan dan Memurnikan Air di Hutan',
                'slug' => 'menemukan-dan-memurnikan-air-di-hutan',
                'category' => 'wilderness',
                'content' => '<p>Air adalah prioritas utama saat tersesat di alam liar. Pelajari cara menemukannya aman.</p>',
                'steps' => [
                    ['title' => 'Cari Sumber Air Mengalir', 'description' => 'Sungai atau mata air lebih aman daripada genangan air diam.'],
                    ['title' => 'Gunakan Teknik Kondensasi', 'description' => 'Ambil air dari uap dedaunan menggunakan kantong plastik bening.'],
                    ['title' => 'Teknik Filtrasi Sederhana', 'description' => 'Gunakan lapisan kerikil, pasir, dan arang untuk menyaring kotoran fisik.'],
                    ['title' => 'Rebus Hingga Mendidih', 'description' => 'Merebus air selama minimal 1 menit adalah cara terbaik membunuh bakteri.'],
                ],
                'image' => 'guides/water-purification.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=6m-Yy0vD_7c',
                'status' => 'published',
            ],
            [
                'title' => 'Membangun Bivak (Shelter) Darurat',
                'slug' => 'membangun-bivak-darurat',
                'category' => 'wilderness',
                'content' => '<p>Cara membuat tempat berlindung sementara menggunakan bahan alam atau terpal.</p>',
                'steps' => [
                    ['title' => 'Pilih Lokasi yang Aman', 'description' => 'Cari tanah datar, bukan di jalur air, dan hindari dahan pohon mati di atasnya.'],
                    ['title' => 'Gunakan Batang Kayu Utama', 'description' => 'Sandarkan batang kayu kuat pada pohon atau penyangga sebagai rangka atas.'],
                    ['title' => 'Susun Dedaunan', 'description' => 'Gunakan daun lebar (seperti palem atau pakis) untuk menutupi rangka agar tahan air.'],
                    ['title' => 'Gunakan Alas Tidur', 'description' => 'Lapisi lantai bivak dengan daun kering agar suhu tubuh tidak hilang ke tanah.'],
                ],
                'image' => 'guides/shelter-building.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=8XmI6_D_pUI',
                'status' => 'published',
            ],
            [
                'title' => 'Memberikan CPR (Resusitasi Jantung Paru)',
                'slug' => 'memberikan-cpr',
                'category' => 'first-aid',
                'content' => '<p>Panduan dasar menyelamatkan nyawa saat seseorang mengalami henti jantung.</p>',
                'steps' => [
                    ['title' => 'Periksa Respon', 'description' => 'Panggil dan tepuk bahu korban. Jika tidak ada respon, segera hubungi ambulans.'],
                    ['title' => 'Posisi Tangan', 'description' => 'Letakkan tumit tangan di tengah dada korban, tumpuk dengan tangan satunya.'],
                    ['title' => 'Tekan dengan Kuat', 'description' => 'Lakukan kompresi sedalam 5-6 cm dengan kecepatan 100-120 kali per menit.'],
                    ['title' => 'Biarkan Dada Mengembang', 'description' => 'Pastikan dada kembali ke posisi semula sebelum penekanan berikutnya.'],
                ],
                'image' => 'guides/cpr-steps.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=-NodDRChVKA',
                'status' => 'published',
            ],
            [
                'title' => 'Menangani Gigitan Ular Berbisa',
                'slug' => 'menangani-gigitan-ular-berbisa',
                'category' => 'first-aid',
                'content' => '<p>Tindakan pertolongan pertama yang tepat dapat mencegah penyebaran racun ular.</p>',
                'steps' => [
                    ['title' => 'Tenangkan Korban', 'description' => 'Panik mempercepat detak jantung dan penyebaran racun melalui darah.'],
                    ['title' => 'Imobilisasi Area Gigitan', 'description' => 'Jangan banyak gerak. Posisikan area gigitan lebih rendah dari jantung jika mungkin.'],
                    ['title' => 'Jangan Mengisap Racun', 'description' => 'Dilarang mengisap racun dengan mulut atau mengikat kencang area gigitan (torniket).'],
                    ['title' => 'Cari Anti Bisa', 'description' => 'Segera bawa ke RS terdekat yang menyediakan Serum Anti Bisa Ular (SABU).'],
                ],
                'image' => 'guides/snake-bite.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=D-hSTX1mDQU',
                'status' => 'published',
            ],
            [
                'title' => 'Navigasi Menggunakan Bintang',
                'slug' => 'navigasi-menggunakan-bintang',
                'category' => 'wilderness',
                'content' => '<p>Pelajari cara menentukan arah saat malam hari tanpa bantuan kompas atau GPS.</p>',
                'steps' => [
                    ['title' => 'Cari Bintang Polaris', 'description' => 'Cari rasi Bintang Biduk (Big Dipper). Dua bintang terluarnya menunjukkan arah ke Polaris (Utara).'],
                    ['title' => 'Rasi Bintang Pari (Crux)', 'description' => 'Di belahan bumi selatan, perpanjang garis rasi bintang ini untuk menemukan arah Selatan.'],
                    ['title' => 'Amati Pergerakan Bintang', 'description' => 'Bintang-bintang "terbit" di Timur dan "tenggelam" di Barat seperti Matahari.'],
                    ['title' => 'Tandai Arah', 'description' => 'Gunakan tongkat atau batu untuk menandai arah yang sudah Anda temukan agar tidak tersesat.'],
                ],
                'image' => 'guides/star-navigation.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=Fm0w-m6n2qg',
                'status' => 'published',
            ],
            [
                'title' => 'Mengobati Luka Bakar Ringan',
                'slug' => 'mengobati-luka-bakar-ringan',
                'category' => 'first-aid',
                'content' => '<p>Cara merawat luka panas akibat api atau cairan panas agar tidak infeksi.</p>',
                'steps' => [
                    ['title' => 'Dinginkan dengan Air Mengalir', 'description' => 'Siram luka dengan air suhu ruang selama 10-20 menit. Jangan gunakan es atau air es.'],
                    ['title' => 'Lepaskan Perhiasan', 'description' => 'Segera lepas cincin atau jam sebelum area yang terbakar membengkak.'],
                    ['title' => 'Jangan Pecahkan Lepuhan', 'description' => 'Lepuhan kulit yang berisi cairan berfungsi melindungi dari infeksi bakteri.'],
                    ['title' => 'Oleskan Salep Luka Bakar', 'description' => 'Gunakan salep antibiotik ringan atau lidah buaya, lalu tutup dengan kasa steril.'],
                ],
                'image' => 'guides/burn-treatment.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=9L-m8Bv-q-g',
                'status' => 'published',
            ],
            [
                'title' => 'Manajemen Sampah Saat Kondisi Darurat',
                'slug' => 'manajemen-sampah-darurat',
                'category' => 'general',
                'content' => '<p>Pengelolaan limbah yang baik mencegah penyebaran penyakit di lokasi pengungsian.</p>',
                'steps' => [
                    ['title' => 'Pisahkan Sampah Organik', 'description' => 'Kubur sisa makanan jauh dari sumber air untuk menghindari lalat dan bau.'],
                    ['title' => 'Kumpulkan Sampah Medis', 'description' => 'Pisahkan perban, masker, atau jarum dalam wadah tertutup tersendiri.'],
                    ['title' => 'Gunakan Metode Gali Lubang', 'description' => 'Buat lubang pembuangan sementara yang cukup dalam dan tutup setelah digunakan.'],
                    ['title' => 'Bakar Sampah Tertentu', 'description' => 'Jika tidak ada layanan angkut sampah, bakar sampah anorganik yang tidak berbahaya.'],
                ],
                'image' => 'guides/waste-management.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=n76eJ_tS_2k',
                'status' => 'published',
            ],
            [
                'title' => 'Psikologi Bertahan Hidup (Mental Resilience)',
                'slug' => 'psikologi-bertahan-hidup',
                'category' => 'general',
                'content' => '<p>Kekuatan mental seringkali lebih penting daripada kekuatan fisik saat situasi krisis.</p>',
                'steps' => [
                    ['title' => 'Terima Situasi', 'description' => 'Berhentilah menyangkal. Akui bahwa Anda sedang dalam bahaya dan mulailah beraksi.'],
                    ['title' => 'Kendalikan Rasa Takut', 'description' => 'Bernapaslah secara mendalam. Takut itu wajar, tapi jangan sampai melumpuhkan pikiran.'],
                    ['title' => 'Buat Rencana Kecil', 'description' => 'Tetapkan target jangka pendek, misalnya "menemukan tempat teduh dalam 1 jam".'],
                    ['title' => 'Tetap Berpikir Positif', 'description' => 'Percayalah Anda akan selamat. Harapan adalah bahan bakar utama untuk bertahan.'],
                ],
                'image' => 'guides/mental-resilience.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=vVnK7c5A7S0',
                'status' => 'published',
            ],
            [
                'title' => 'Penggunaan APAR (Alat Pemadam Api Ringan)',
                'slug' => 'penggunaan-apar-yang-benar',
                'category' => 'fire',
                'content' => '<p>Ingat teknik PASS saat menggunakan tabung pemadam untuk memadamkan api kecil.</p>',
                'steps' => [
                    ['title' => 'Pull (Tarik Pin)', 'description' => 'Tarik pin pengaman tabung. Pastikan segel sudah terlepas.'],
                    ['title' => 'Aim (Arahkan)', 'description' => 'Arahkan corong atau nozel ke pangkal/pusat api, bukan ke bagian atas lidah api.'],
                    ['title' => 'Squeeze (Tekan)', 'description' => 'Tekan tuas untuk mengeluarkan bahan pemadam dari dalam tabung.'],
                    ['title' => 'Sweep (Sapukan)', 'description' => 'Sapukan moncong tabung dari kiri ke kanan secara merata hingga api padam.'],
                ],
                'image' => 'guides/apar-guide.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=07yU_CqZl5w',
                'status' => 'published',
            ],
            [
                'title' => 'Sanitasi dan Kebersihan di Pengungsian',
                'slug' => 'sanitasi-di-pengungsian',
                'category' => 'general',
                'content' => '<p>Cara mencegah wabah penyakit menular saat tinggal di tempat penampungan sementara.</p>',
                'steps' => [
                    ['title' => 'Rajin Cuci Tangan', 'description' => 'Gunakan sabun atau hand sanitizer sesering mungkin, terutama sebelum makan.'],
                    ['title' => 'Jaga Jarak Aman', 'description' => 'Hindari berkerumun terlalu padat di dalam tenda jika memungkinkan untuk mencegah flu.'],
                    ['title' => 'Etika Batuk dan Bersin', 'description' => 'Gunakan masker atau tutup mulut dengan siku bagian dalam saat bersin.'],
                    ['title' => 'Pastikan Makanan Matang', 'description' => 'Hanya konsumsi makanan yang baru dimasak atau makanan dalam kemasan yang masih utuh.'],
                ],
                'image' => 'guides/sanitation-camp.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=Zt_t142m9-c',
                'status' => 'published',
            ],
            [
                'title' => 'Navigasi Aman Saat Badai Salju (Blizzard)',
                'slug' => 'navigasi-aman-saat-badai-salju',
                'category' => 'storm',
                'content' => '<p>Tips bertahan hidup saat terjebak dalam cuaca dingin ekstrem dan jarak pandang nol.</p>',
                'steps' => [
                    ['title' => 'Jangan Tinggalkan Kendaraan', 'description' => 'Jika terjebak saat mengemudi, tetaplah di dalam mobil. Mobil adalah shelter terbaik Anda.'],
                    ['title' => 'Gunakan Pakaian Berlapis', 'description' => 'Pakai pakaian wol atau sintetis. Jangan gunakan katun karena menyimpan kelembapan.'],
                    ['title' => 'Hemat Energi', 'description' => 'Jangan melakukan aktivitas fisik berat yang memicu keringat. Keringat akan mendinginkan tubuh dengan cepat.'],
                    ['title' => 'Jaga Sirkulasi Udara', 'description' => 'Pastikan knalpot mobil tidak tersumbat salju untuk mencegah keracunan gas karbon monoksida.'],
                ],
                'image' => 'guides/blizzard-safety.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=Z_a7zD4k_tQ',
                'status' => 'published',
            ],
            [
                'title' => 'Menjaga Keamanan Hewan Peliharaan Saat Bencana',
                'slug' => 'keamanan-hewan-peliharaan',
                'category' => 'general',
                'content' => '<p>Pastikan anggota keluarga berbulu Anda juga selamat saat situasi darurat terjadi.</p>',
                'steps' => [
                    ['title' => 'Sediakan Pet Kit', 'description' => 'Siapkan makanan, air, dan obat-obatan hewan untuk kebutuhan minimal 3-7 hari.'],
                    ['title' => 'Gunakan Kalung Identitas', 'description' => 'Pastikan hewan memakai kalung berisi nama dan nomor telepon Anda yang bisa dihubungi.'],
                    ['title' => 'Bawa Kandang Portabel', 'description' => 'Siapkan pet carrier agar hewan lebih mudah dibawa saat evakuasi mendadak.'],
                    ['title' => 'Cari Tempat Ramah Hewan', 'description' => 'Daftar penginapan atau shelter yang memperbolehkan membawa hewan peliharaan.'],
                ],
                'image' => 'guides/pet-safety.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0k7y_p7y0y0',
                'status' => 'published',
            ],
            [
                'title' => 'Sinyal Darurat SOS di Alam Liar',
                'slug' => 'sinyal-darurat-sos',
                'category' => 'wilderness',
                'content' => '<p>Cara meminta bantuan kepada kru penyelamat menggunakan peralatan yang ada di sekitar.</p>',
                'steps' => [
                    ['title' => 'Sinyal Asap Terang', 'description' => 'Buat tiga api unggun dalam bentuk segitiga. Tambahkan dedaunan hijau agar asapnya lebat.'],
                    ['title' => 'Pantulan Cermin', 'description' => 'Gunakan cermin atau benda mengkilap lainnya untuk memantulkan sinar matahari ke arah pesawat/helikopter.'],
                    ['title' => 'Tanda Tanah Besar', 'description' => 'Tulis "SOS" besar di tanah menggunakan batu, kayu, atau menggali pasir di area terbuka.'],
                    ['title' => 'Peluit Darurat', 'description' => 'Tiga tiupan pendek berturut-turut adalah sinyal universal untuk meminta bantuan.'],
                ],
                'image' => 'guides/sos-signals.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=Z_y-y9p9p9p',
                'status' => 'published',
            ],
            [
                'title' => 'Mengenali Tanaman Hutan yang Aman Dimakan',
                'slug' => 'mengenali-tanaman-hutan-aman',
                'category' => 'wilderness',
                'content' => '<p>Hati-hati dalam memilih makanan di hutan. Salah pilih bisa berakibat keracunan fatal.</p>',
                'steps' => [
                    ['title' => 'Gunakan Tes Rasa Sederhana', 'description' => 'Tempelkan sedikit getah/potongan ke bibir. Tunggu 15 menit, jika tidak gatal/panas, baru coba sedikit.'],
                    ['title' => 'Hindari Getah Putih', 'description' => 'Mayoritas tanaman dengan getah berwarna putih seperti susu bersifat racun.'],
                    ['title' => 'Kenali Jamur', 'description' => 'Sangat disarankan hindari semua jenis jamur liar jika Anda bukan ahlinya.'],
                    ['title' => 'Cari Buah yang Dimakan Burung', 'description' => 'Biasanya buah yang aman bagi burung juga aman bagi manusia, tapi tetaplah waspada.'],
                ],
                'image' => 'guides/edible-plants.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0p7y_p7y0z0',
                'status' => 'published',
            ],
            [
                'title' => 'Teknik Mengangkat Korban Cedera (Evakuasi Mandiri)',
                'slug' => 'teknik-mengangkat-korban',
                'category' => 'first-aid',
                'content' => '<p>Cara memindahkan korban ke tempat aman tanpa memperparah cederanya.</p>',
                'steps' => [
                    ['title' => 'Metode Seretan (Drag)', 'description' => 'Gunakan selimut atau tarik bahu korban jika jaraknya dekat dan lantai rata.'],
                    ['title' => 'Menopang Bahu', 'description' => 'Untuk korban yang masih bisa berjalan sedikit, posisikan tangan mereka di leher Anda.'],
                    ['title' => 'Gendongan Pemadam (Fireman Carry)', 'description' => 'Teknik paling efisien untuk membawa satu orang pingsan dalam jarak menengah.'],
                    ['title' => 'Gunakan Tandu Darurat', 'description' => 'Buat tandu menggunakan dua batang kayu dan jaket atau sarung yang kuat.'],
                ],
                'image' => 'guides/victim-carry.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0q7y_p7y0a0',
                'status' => 'published',
            ],
            [
                'title' => 'Membuat Penjernih Air Arang Sederhana',
                'slug' => 'membuat-penjernih-air-arang',
                'category' => 'general',
                'content' => '<p>Gunakan bahan di sekitar untuk menjernihkan air keruh menjadi layak konsumsi.</p>',
                'steps' => [
                    ['title' => 'Siapkan Botol Plastik', 'description' => 'Potong bagian bawah botol dan posisikan terbalik.'],
                    ['title' => 'Susun Lapisan', 'description' => 'Isi dengan kapas/kain, diikuti arang hancur, pasir halus, pasir kasar, dan kerikil.'],
                    ['title' => 'Alirkan Air', 'description' => 'Tuang air keruh dari atas. Air akan keluar perlahan di bawah dalam kondisi lebih jernih.'],
                    ['title' => 'Tetap Rebus Air', 'description' => 'Ingat, filtrasi ini hanya menghilangkan kotoran fisik, bukan bakteri. Tetaplah merebusnya.'],
                ],
                'image' => 'guides/charcoal-filter.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0r7y_p7y0b0',
                'status' => 'published',
            ],
            [
                'title' => 'Menghadapi Serangan Panik Saat Bencana',
                'slug' => 'menghadapi-serangan-panik',
                'category' => 'general',
                'content' => '<p>Cara menenangkan diri atau orang lain agar tetap bisa berpikir logis di situasi kritis.</p>',
                'steps' => [
                    ['title' => 'Teknik 5-4-3-2-1', 'description' => 'Sebutkan 5 benda yang dilihat, 4 yang bisa disentuh, 3 suara, 2 bau, dan 1 rasa.'],
                    ['title' => 'Atur Pernapasan Kotak', 'description' => 'Tarik napas 4 detik, tahan 4 detik, buang 4 detik, tahan 4 detik. Ulangi.'],
                    ['title' => 'Fokus pada Satu Tugas', 'description' => 'Alihkan pikiran dari bencana dengan fokus melakukan satu hal kecil yang berguna.'],
                    ['title' => 'Bicara pada Diri Sendiri', 'description' => 'Katakan dengan keras, "Saya aman sekarang, saya bisa melewati ini step-by-step".'],
                ],
                'image' => 'guides/panic-management.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0s7y_p7y0c0',
                'status' => 'published',
            ],
            [
                'title' => 'Keamanan Mengemudi Saat Hujan Lebat',
                'slug' => 'keamanan-mengemudi-saat-hujan',
                'category' => 'general',
                'content' => '<p>Hindari kecelakaan dan mobil mogok saat terjebak hujan badai di perjalanan.</p>',
                'steps' => [
                    ['title' => 'Nyalakan Lampu Utama', 'description' => 'Bukan lampu hazard. Lampu utama membantu Anda melihat dan terlihat dalam jarak pandang terbatas.'],
                    ['title' => 'Kurangi Kecepatan', 'description' => 'Jaga jarak pengereman lebih jauh dari biasanya karena jalanan licin (aquaplaning).'],
                    ['title' => 'Waspadai Genangan Tinggi', 'description' => 'Jangan nekat menerjang banjir jika ketinggian air sudah mencapai knalpot atau filter udara.'],
                    ['title' => 'Cari Tempat Berhenti Aman', 'description' => 'Jika hujan terlalu deras hingga pandangan nol, berhentilah di bahu jalan jauh dari pepohonan.'],
                ],
                'image' => 'guides/driving-rain.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0t7y_p7y0d0',
                'status' => 'published',
            ],
            [
                'title' => 'Dasar-Dasar Tali Temali (Simpul Darurat)',
                'slug' => 'dasar-tali-temali-darurat',
                'category' => 'wilderness',
                'content' => '<p>Beberapa simpul penting yang sangat berguna untuk membangun shelter atau mengikat beban.</p>',
                'steps' => [
                    ['title' => 'Simpul Mati (Square Knot)', 'description' => 'Digunakan untuk menyambung dua tali yang berukuran sama besar.'],
                    ['title' => 'Simpul Pangkal (Clove Hitch)', 'description' => 'Simpul awal yang paling sering digunakan untuk mengikat tali pada tiang atau pohon.'],
                    ['title' => 'Simpul Kambing (Bowline)', 'description' => 'Simpul paling aman yang tidak akan menjerat leher, cocok untuk penyelamatan korban.'],
                    ['title' => 'Simpul Nelayan (Fisherman Knot)', 'description' => 'Sangat kuat untuk menyambung dua tali yang licin atau berbeda bahan.'],
                ],
                'image' => 'guides/rope-knots.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0u7y_p7y0e0',
                'status' => 'published',
            ],
            [
                'title' => 'Evakuasi Penyandang Disabilitas Saat Bencana',
                'slug' => 'evakuasi-disabilitas-darurat',
                'category' => 'general',
                'content' => '<p>Pastikan setiap orang, terlepas dari keterbatasan fisiknya, mendapatkan akses evakuasi yang adil.</p>',
                'steps' => [
                    ['title' => 'Bangun Sistem Buddy', 'description' => 'Pastikan ada orang terdekat yang ditunjuk khusus untuk membantu saat sirine berbunyi.'],
                    ['title' => 'Siapkan Alat Bantu Cadangan', 'description' => 'Simpan tongkat, kursi roda manual, atau baterai alat pendengaran di dekat pintu keluar.'],
                    ['title' => 'Gunakan Tanda Visual/Getar', 'description' => 'Untuk penyandang tuna rungu, pasang lampu strobo sebagai tanda peringatan dini.'],
                    ['title' => 'Berikan Instruksi Jelas', 'description' => 'Bicara dengan tenang dan langsung ke arah wajah. Jangan menyeret kursi roda tanpa izin.'],
                ],
                'image' => 'guides/disability-safety.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0v7y_p7y0f0',
                'status' => 'published',
            ],
            [
                'title' => 'Mengevaluasi Kelayakan Bangunan Pasca Gempa',
                'slug' => 'evaluasi-bangunan-pasca-gempa',
                'category' => 'earthquake',
                'content' => '<p>Jangan terburu-buru masuk kembali. Pastikan struktur rumah Anda masih aman ditinggali.</p>',
                'steps' => [
                    ['title' => 'Cek Retakan Struktur', 'description' => 'Waspadai retakan diagonal (bentuk X) pada tembok atau retakan besar pada pilar rumah.'],
                    ['title' => 'Periksa Kemiringan Bangunan', 'description' => 'Gunakan pendulum sederhana untuk melihat apakah bangunan sudah miring secara ekstrem.'],
                    ['title' => 'Tes Pintu dan Jendela', 'description' => 'Jika sulit dibuka/ditutup, tandanya struktur rumah sudah bergeser atau melengkung.'],
                    ['title' => 'Waspadai Kebocoran Gas/Air', 'description' => 'Cium bau gas atau periksa meteran air sebelum menyalakan alat listrik apa pun.'],
                ],
                'image' => 'images/guides/house-damage-check.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0w7y_p7y0g0',
                'status' => 'published',
            ],
            [
                'title' => 'Pertolongan Pertama pada Tersedak (Heimlich Maneuver)',
                'slug' => 'pertolongan-pertama-tersedak',
                'category' => 'first-aid',
                'content' => '<p>Tindakan cepat untuk mengeluarkan benda asing yang menyumbat jalan napas.</p>',
                'steps' => [
                    ['title' => 'Dorong Batuk', 'description' => 'Jika korban masih bisa batuk atau bicara, minta mereka terus batuk sekeras mungkin.'],
                    ['title' => 'Lakukan 5 Tepukan Punggung', 'description' => 'Bungkukkan korban dan tepuk punggung di antara tulang belikat menggunakan tumit tangan.'],
                    ['title' => 'Lakukan 5 Hentakan Perut', 'description' => 'Posisikan tangan di atas pusar dan tarik ke dalam lalu ke atas dengan kuat.'],
                    ['title' => 'Ulangi Sampai Keluar', 'description' => 'Lakukan siklus 5-5 ini sampai benda keluar atau korban hilang kesadaran (lalu lakukan CPR).'],
                ],
                'image' => 'guides/choking-help.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0x7y_p7y0h0',
                'status' => 'published',
            ],
            [
                'title' => 'Penanganan Keracunan Makanan Darurat',
                'slug' => 'penanganan-keracunan-makanan',
                'category' => 'first-aid',
                'content' => '<p>Langkah-langkah menetralisir racun dan mencegah dehidrasi akibat muntah/diare.</p>',
                'steps' => [
                    ['title' => 'Hentikan Makan/Minum', 'description' => 'Biarkan perut istirahat selama beberapa jam setelah gejala muncul.'],
                    ['title' => 'Berikan Oralit atau Air Kelapa', 'description' => 'Ganti cairan dan elektrolit yang hilang secara perlahan, sedikit demi sedikit.'],
                    ['title' => 'Gunakan Norit (Arang Aktif)', 'description' => 'Tablet arang aktif dapat membantu menyerap racun yang masih ada di pencernaan.'],
                    ['title' => 'Cari Bantuan Medis', 'description' => 'Jika muncul demam tinggi, darah pada tinja, atau muntah terus-menerus.'],
                ],
                'image' => 'guides/food-poisoning.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0y7y_p7y0i0',
                'status' => 'published',
            ],
            [
                'title' => 'Teknik Packing Carrier yang Ergonomis',
                'slug' => 'teknik-packing-carrier',
                'category' => 'wilderness',
                'content' => '<p>Cara menyusun barang di dalam tas ransel agar beban terasa lebih ringan dan stabil saat berjalan jauh.</p>',
                'steps' => [
                    ['title' => 'Barang Ringan di Bawah', 'description' => 'Letakkan sleeping bag atau bantal di bagian paling bawah tas.'],
                    ['title' => 'Barang Berat di Tengah', 'description' => 'Posisikan botol air, logistik berat, dan nesting sedekat mungkin dengan punggung Anda.'],
                    ['title' => 'Barang Sering Digunakan di Atas', 'description' => 'Taruh jas hujan, P3K, dan snack di bagian atas atau saku kepala ransel.'],
                    ['title' => 'Seimbangkan Kiri dan Kanan', 'description' => 'Pastikan beban tidak berat sebelah agar tidak membebani satu sisi pundak.'],
                ],
                'image' => 'guides/backpacking-packing.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=0z7y_p7y0j0',
                'status' => 'published',
            ],
            [
                'title' => 'Menghadapi Bahaya Hewan Liar (Beruang/Harimau)',
                'slug' => 'menghadapi-hewan-liar',
                'category' => 'wilderness',
                'content' => '<p>Ketahuilah perilaku hewan liar agar Anda tidak dianggap sebagai ancaman atau mangsa.</p>',
                'steps' => [
                    ['title' => 'Jangan Lari', 'description' => 'Lari akan memicu insting predator hewan untuk mengejar Anda. Tetap tenang.'],
                    ['title' => 'Tampaklah Lebih Besar', 'description' => 'Rentangkan tangan atau buka jaket Anda dengan lebar. Jangan lakukan kontak mata langsung.'],
                    ['title' => 'Mundur Perlahan', 'description' => 'Berjalan mundur secara perlahan sambil terus memperhatikan posisi hewan tersebut.'],
                    ['title' => 'Beri Suara Keras', 'description' => 'Jika hewan mendekat, berteriaklah dengan suara rendah dan lantang untuk menakutinya.'],
                ],
                'image' => 'guides/wildlife-encounter.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=1a7y_p7y0k0',
                'status' => 'published',
            ],
            [
                'title' => 'Pertolongan Pertama Terkena Gas Air Mata',
                'slug' => 'pertolongan-gas-air-mata',
                'category' => 'general',
                'content' => '<p>Jangan gunakan odol! Pelajari cara menetralkan perih akibat gas air mata yang benar.</p>',
                'steps' => [
                    ['title' => 'Cari Udara Segar', 'description' => 'Segera lari ke tempat tinggi atau yang hembusan anginnya kencang agar gas hilang.'],
                    ['title' => 'Basuh dengan Air/Cairan Infus', 'description' => 'Bilas mata dari arah hidung ke luar secara perlahan dengan air bersih yang mengalir.'],
                    ['title' => 'Jangan Mengucek Mata', 'description' => 'Mengucek mata akan membuat partikel gas semakin menusuk dan merusak kornea.'],
                    ['title' => 'Ganti Pakaian', 'description' => 'Segera ganti baju yang terpapar gas karena partikel gas bisa menempel lama di kain.'],
                ],
                'image' => 'guides/teargas-treatment.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=1b7y_p7y0l0',
                'status' => 'published',
            ],
            [
                'title' => 'Komunikasi Radio Saat Jaringan Seluler Mati',
                'slug' => 'komunikasi-radio-darurat',
                'category' => 'general',
                'content' => '<p>Cara menggunakan Handy Talky (HT) untuk tetap terhubung saat tower BTS roboh.</p>',
                'steps' => [
                    ['title' => 'Kenali Frekuensi Darurat', 'description' => 'Cari tahu frekuensi lokal RAPI atau ORARI di wilayah Anda berada.'],
                    ['title' => 'Berbicara Bergantian', 'description' => 'Tekan tombol PTT, bicara singkat dan jelas, lalu lepas tombol untuk mendengarkan.'],
                    ['title' => 'Sebutkan Identitas', 'description' => 'Gunakan callsign atau nama panggil agar kru penyelamat mengenali posisi Anda.'],
                    ['title' => 'Hemat Baterai', 'description' => 'Hanya gunakan radio untuk informasi penting. Matikan jika tidak digunakan.'],
                ],
                'image' => 'guides/radio-comm.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=1c7y_p7y0m0',
                'status' => 'published',
            ],
            [
                'title' => 'Membangun Perangkap Ikan Sederhana di Sungai',
                'slug' => 'perangkap-ikan-hutan',
                'category' => 'wilderness',
                'content' => '<p>Mendapatkan protein hewani tanpa energi besar menggunakan jebakan pasif.</p>',
                'steps' => [
                    ['title' => 'Membuat "V" Trap', 'description' => 'Susun batu membentuk huruf V dengan lubang kecil yang mengarah ke bagian sempit.'],
                    ['title' => 'Gunakan Botol Bekas', 'description' => 'Potong leher botol, balikkan corongnya ke dalam, dan beri sedikit umpan di dalamnya.'],
                    ['title' => 'Cari Area Dangkal', 'description' => 'Pasang perangkap di pinggiran sungai yang airnya tidak terlalu deras.'],
                    ['title' => 'Cek Secara Berkala', 'description' => 'Periksa perangkap setiap pagi atau sore hari untuk melihat hasilnya.'],
                ],
                'image' => 'guides/fishing-trap.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=1d7y_p7y0n0',
                'status' => 'published',
            ],
            [
                'title' => 'Menjaga Kebersihan Kelamin di Pengungsian',
                'slug' => 'higiene-reproduksi-darurat',
                'category' => 'general',
                'content' => '<p>Kesehatan reproduksi sering terabaikan saat bencana, pelajari cara menjaganya agar tetap sehat.</p>',
                'steps' => [
                    ['title' => 'Selalu Gunakan Air Bersih', 'description' => 'Prioritaskan penggunaan air bersih yang terbatas untuk membersihkan area privat.'],
                    ['title' => 'Ganti Pembalut Rutin', 'description' => 'Bagi wanita, usahakan mengganti pembalut setiap 4-6 jam sekali.'],
                    ['title' => 'Hindari Pakaian Dalam Lembap', 'description' => 'Keringkan pakaian dalam dengan benar untuk menghindari munculnya jamur kulit.'],
                    ['title' => 'Laporkan Jika Ada Keluhan', 'description' => 'Segera hubungi pos kesehatan jika merasa gatal atau nyeri yang tidak biasa.'],
                ],
                'image' => 'guides/reproduction-health.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=1e7y_p7y0o0',
                'status' => 'published',
            ],
            [
                'title' => 'Menghadapi Ancaman Kekerasan di Area Bencana',
                'slug' => 'keamanan-diri-pengungsian',
                'category' => 'general',
                'content' => '<p>Langkah-langkah preventif menjaga keamanan diri dan keluarga dari pelaku kriminalitas pasca krisis.</p>',
                'steps' => [
                    ['title' => 'Jangan Bepergian Sendirian', 'description' => 'Selalu ajak teman atau anggota keluarga jika ingin ke toilet atau luar area tenda.'],
                    ['title' => 'Sediakan Alat Bela Diri', 'description' => 'Miliki peluit atau senter terang di dekat tangan untuk menarik perhatian jika diganggu.'],
                    ['title' => 'Tetap di Area Terang', 'description' => 'Usahakan beraktivitas di titik-titik yang banyak orang dan mendapat pencahayaan lampu.'],
                    ['title' => 'Laporkan Orang Mencurigakan', 'description' => 'Segera lapor ke petugas keamanan atau TNI/Polri jika melihat aktivitas mencurigakan.'],
                ],
                'image' => 'guides/self-safety-camp.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=1f7y_p7y0p0',
                'status' => 'published',
            ],
            [
                'title' => 'Pertolongan Pertama pada Patah Tulang (Bidai)',
                'slug' => 'pertolongan-patah-tulang',
                'category' => 'first-aid',
                'content' => '<p>Cara memasang penyangga sementara untuk membatasi gerak tulang yang patah agar tidak makin parah.</p>',
                'steps' => [
                    ['title' => 'Jangan Gerakkan Korban', 'description' => 'Kecuali jika lokasi sudah tidak aman lagi untuk ditempati.'],
                    ['title' => 'Gunakan Papan Kaku', 'description' => 'Cari kayu, bambu, atau karton tebal sebagai penyangga di kedua sisi tulang yang patah.'],
                    ['title' => 'Ikat dengan Kuat', 'description' => 'Ikat bidai menggunakan kain atau tali, tapi pastikan tidak menghentikan aliran darah.'],
                    ['title' => 'Cek Sensasi di Jari', 'description' => 'Pastikan korban masih bisa menggerakkan jari-jarinya setelah bidai dipasang.'],
                ],
                'image' => 'guides/splinting-guide.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=1g7y_p7y0q0',
                'status' => 'published',
            ],
            [
                'title' => 'Keamanan Listrik Rumah Pasca Banjir',
                'slug' => 'listrik-aman-pasca-banjir',
                'category' => 'general',
                'content' => '<p>Jangan langsung menyalakan stop kontak! Pelajari cara aman mengaktifkan kembali listrik rumah Anda.</p>',
                'steps' => [
                    ['title' => 'Pastikan Kondisi Kering', 'description' => 'Lantai, stop kontak, dan kabel harus benar-benar kering sebelum dialiri listrik kembali.'],
                    ['title' => 'Gunakan Teknisi Ahli', 'description' => 'Sangat disarankan meminta bantuan PLN atau teknisi resmi untuk memeriksa instalasi.'],
                    ['title' => 'Bersihkan Sisa Lumpur', 'description' => 'Lumpur basah bisa menghantarkan arus pendek (korsleting) yang berakibat kebakaran.'],
                    ['title' => 'Nyalakan Bertahap', 'description' => 'Nyalakan MCB utama terlebih dahulu, baru kemudian nyalakan saklar lampu satu per satu.'],
                ],
                'image' => 'guides/electrical-safety-flood.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=1h7y_p7y0r0',
                'status' => 'published',
            ],
            [
                'title' => 'Mengatasi Tersedak pada Bayi (Infant Choking)',
                'slug' => 'mengatasi-tersedak-bayi',
                'category' => 'first-aid',
                'content' => '<p>Hati-hati, penanganan bayi tersedak berbeda dengan orang dewasa. Ikuti cara aman ini.</p>',
                'steps' => [
                    ['title' => 'Tepukan Punggung (Back Slaps)', 'description' => 'Posisikan bayi tengkurap di lengan Anda dan berikan 5 tepukan lembut tapi mantap di punggung.'],
                    ['title' => 'Hentakan Dada (Chest Thrusts)', 'description' => 'Balikkan bayi dan gunakan dua jari untuk menekan tengah dada sebanyak 5 kali.'],
                    ['title' => 'Cek Mulut', 'description' => 'Jika benda terlihat, ambil dengan jari. Jangan memasukkan jari jika benda tidak terlihat.'],
                    ['title' => 'Ulangi Perlahan', 'description' => 'Lakukan siklus 5:5 ini dengan sangat hati-hati karena tulang bayi masih rapuh.'],
                ],
                'image' => 'guides/baby-choking.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=1i7y_p7y0s0',
                'status' => 'published',
            ],
            [
                'title' => 'Mengevakuasi Ibu Hamil Saat Situasi Darurat',
                'slug' => 'evakuasi-ibu-hamil',
                'category' => 'general',
                'content' => '<p>Penanganan khusus bagi wanita hamil untuk menjamin keselamatan ibu dan calon bayi.</p>',
                'steps' => [
                    ['title' => 'Posisikan Miring ke Kiri', 'description' => 'Saat beristirahat, minta ibu hamil miring ke kiri untuk sirkulasi darah yang lebih lancar.'],
                    ['title' => 'Bawa Buku KIA/Kesehatan', 'description' => 'Pastikan rekam medis kehamilan ikut terbawa agar dokter di pengungsian tahu kondisinya.'],
                    ['title' => 'Hindari Guncangan Kuat', 'description' => 'Lakukan evakuasi dengan gerakan yang sehalus mungkin untuk meminimalkan trauma rahim.'],
                    ['title' => 'Pastikan Kecukupan Nutrisi', 'description' => 'Prioritaskan makanan segar dan suplemen vitamin yang biasanya dikonsumsi ibu hamil.'],
                ],
                'image' => 'guides/pregnant-safety.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=1j7y_p7y0t0',
                'status' => 'published',
            ],
            [
                'title' => 'Membaca Peta Navigasi Darat Sederhana',
                'slug' => 'membaca-peta-navigasi',
                'category' => 'wilderness',
                'content' => '<p>Keterampilan membaca kontur dan simbol peta untuk menemukan jalan pulang tanpa GPS.</p>',
                'steps' => [
                    ['title' => 'Pahami Orientasi Utara', 'description' => 'Pastikan bagian atas peta menghadap ke arah Utara yang sebenarnya.'],
                    ['title' => 'Pelajari Garis Kontur', 'description' => 'Garis yang rapat menandakan tebing curam, sedangkan garis renggang menandakan lahan landai.'],
                    ['title' => 'Gunakan Fitur Alam', 'description' => 'Cocokkan bentuk gunung, lembah, atau sungai yang ada di depan mata dengan gambar di peta.'],
                    ['title' => 'Tentukan Posisi (Resection)', 'description' => 'Pilih dua benda alam yang mencolok untuk menarik garis silang koordinat posisi Anda saat ini.'],
                ],
                'image' => 'guides/map-reading.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=1k7y_p7y0u0',
                'status' => 'published',
            ],
        ];

        foreach ($guides as $guide) {
            Guide::create($guide);
        }
    }
}
